[package]
name = "k-fold_cross_validation"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
egui = "0.22.0"
rayon = "1.7.0"
commands = {path="commands/"}

[workspace]
members = ["commands/"]